"""
DXF Generation Constants
Centralized configuration values for DXF generation
"""

# Coordinate System
EARTH_RADIUS_METERS = 6378137
MAX_COORDINATE_VALUE = 1e11
DEFAULT_COORDINATE = 0.0

# Grid and Resolution
DEFAULT_GRID_SIZE = 12
TERRAIN_RESOLUTION = 100
CONTOUR_INTERVAL = 1.0
HIGH_RES_CONTOUR_INTERVAL = 0.5

# Spatial Analysis
POWER_LINE_BUFFER_METERS = 5.0
STREET_LAMP_COVERAGE_METERS = 15.0
IDEAL_LAMP_SPACING_METERS = 30.0

# Text and Labels
DEFAULT_TEXT_HEIGHT = 2.5
DEFAULT_TITLE_HEIGHT = 4.0
DEFAULT_SUBTITLE_HEIGHT = 3.0
DEFAULT_SMALL_TEXT_HEIGHT = 2.0
MIN_LINE_LENGTH_FOR_LABEL = 0.1
LABEL_ROTATION_SAMPLE_START = 0.45
LABEL_ROTATION_SAMPLE_END = 0.55

# Street Widths (meters)
STREET_WIDTHS = {
    'motorway': 7.5,
    'trunk': 7.0,
    'primary': 6.0,
    'secondary': 5.5,
    'tertiary': 5.0,
    'residential': 4.0,
    'service': 3.0,
    'unclassified': 3.5,
    'default': 3.0
}

# Layer Names (all prefixed with TOPO_ for ABNT standardization)
LAYER_EDIFICACAO = 'TOPO_EDIFICACAO'
LAYER_VEGETACAO = 'TOPO_VEGETACAO'
LAYER_EQUIPAMENTOS = 'TOPO_EQUIPAMENTOS'
LAYER_HIDROGRAFIA = 'TOPO_HIDROGRAFIA'
LAYER_INFRA_POWER_HV = 'TOPO_INFRA_POWER_HV'
LAYER_INFRA_POWER_LV = 'TOPO_INFRA_POWER_LV'
LAYER_INFRA_TELECOM = 'TOPO_INFRA_TELECOM'
LAYER_MOBILIARIO_URBANO = 'TOPO_MOBILIARIO_URBANO'
LAYER_TEXTO = 'TOPO_TEXTO'
LAYER_QUADRO = 'TOPO_QUADRO'

# Phase 9: AS-IS Restrictions & Land Use
LAYER_RESTRICAO_APP_30M = 'TOPO_RESTRICAO_APP_30M'
LAYER_USO_RESIDENCIAL = 'TOPO_USO_RESIDENCIAL'
LAYER_USO_COMERCIAL = 'TOPO_USO_COMERCIAL'
LAYER_USO_INDUSTRIAL = 'TOPO_USO_INDUSTRIAL'
LAYER_USO_VEGETACAO = 'TOPO_USO_VEGETACAO'

# Street-specific layers
LAYER_VIAS_MOTORWAY = 'TOPO_VIAS_MOTORWAY'
LAYER_VIAS_TRUNK = 'TOPO_VIAS_TRUNK'
LAYER_VIAS_PRIMARY = 'TOPO_VIAS_PRIMARY'
LAYER_VIAS_SECONDARY = 'TOPO_VIAS_SECONDARY'
LAYER_VIAS_TERTIARY = 'TOPO_VIAS_TERTIARY'
LAYER_VIAS_RESIDENTIAL = 'TOPO_VIAS_RESIDENTIAL'
LAYER_VIAS_SERVICE = 'TOPO_VIAS_SERVICE'
LAYER_VIAS_UNCLASSIFIED = 'TOPO_VIAS_UNCLASSIFIED'
LAYER_VIAS_PEDESTRIAN = 'TOPO_VIAS_PEDESTRIAN'
LAYER_VIAS_FOOTWAY = 'TOPO_VIAS_FOOTWAY'
LAYER_VIAS_CYCLEWAY = 'TOPO_VIAS_CYCLEWAY'
LAYER_VIAS_PATH = 'TOPO_VIAS_PATH'
LAYER_VIAS_DEFAULT = 'TOPO_VIAS_DEFAULT'

# Curb offset layer
LAYER_VIAS_MEIO_FIO = 'TOPO_VIAS_MEIO_FIO'

# Fallback layer
LAYER_DEFAULT = '0'

# File and Export
MAX_FILENAME_LENGTH = 255
DXF_VERSION = 'R2013'
# NOTE: Do not update PROJECT_VERSION manually. Use ./scripts/update-version.sh instead.
# See VERSIONING.md for details about version management.
PROJECT_VERSION = '1.0.0'

# Validation
MIN_POLYGON_POINTS = 3
MIN_LINE_POINTS = 2
MAX_FETCH_RADIUS_METERS = 5000
COORDINATE_EPSILON = 1e-5
MIN_ANGLE_DEGREES = -90
MAX_ANGLE_DEGREES = 90
ANGLE_FLIP_OFFSET = 180

# Paper Sizes (mm)
A3_WIDTH = 420
A3_HEIGHT = 297
TITLE_BLOCK_WIDTH = 185
TITLE_BLOCK_HEIGHT = 50

# Margins and Spacing
BORDER_MARGIN = 20
VIEWPORT_OFFSET_Y = 20
VIEWPORT_MARGIN = 40
TITLE_BLOCK_SUBDIVISIONS = 25

# Logging
MAX_LOG_MESSAGE_LENGTH = 200
