export function useAppSidebarProps({
  settings,
  center,
  searchQuery,
  setSearchQuery,
  isSearching,
  handleSearch,
  selectionMode,
  handleSelectionModeChange,
  radius,
  handleRadiusChange,
  saveSnapshot,
  handleFetchAndAnalyze,
  isProcessing,
  isPolygonValid,
  setBtNetworkScenario,
  setBtEditorMode,
  btNetworkScenario,
  btEditorMode,
  btTopology,
  dgTopologySource,
  btAccumulatedByPole,
  btSummary,
  btPointDemandKva,
  btTransformerDebugById,
  btPoleCoordinateInput,
  setBtPoleCoordinateInput,
  handleBtInsertPoleByCoordinates,
  pendingPendingBtEdge,
  pendingNormalClassificationPoles,
  handleResetBtTopology,
  updateBtTopology,
  updateProjectType,
  updateClandestinoAreaM2,
  handleBtSelectedPoleChange,
  handleBtSelectedTransformerChange,
  handleBtSelectedEdgeChange,
  handleBtRenamePole,
  handleBtRenameTransformer,
  handleBtSetEdgeChangeFlag,
  handleBtSetPoleChangeFlag,
  handleBtTogglePoleCircuitBreak,
  handleBtSetTransformerChangeFlag,
  btClandestinoDisplay,
  btTransformersDerived,
  requestCriticalConfirmation,
  handleTriggerTelescopicAnalysis,
  isDgOptimizing,
  dgResult,
  dgError,
  dgActiveAltIndex,
  handleRunDgOptimization,
  handleAcceptDgAll,
  handleAcceptDgTrafoOnly,
  handleDiscardDgResult,
  setDgActiveAltIndex,
  isPreviewActive,
  setIsPreviewActive,
  selectedPoleId,
  selectedPoleIds,
  selectedEdgeId,
  selectedTransformerId,
  setSelectedPoleId,
  setSelectedPoleIds,
  setSelectedEdgeId,
  setSelectedTransformerId,
  mtTopology,
  osmData,
  stats,
  analysisText,
  terrainData,
  error,
  handleDownloadDxf,
  handleDownloadCoordinatesCsv,
  isDownloading,
  showToast,
}: any) {
  const sidebarSelectionControlsProps = {
    locale: settings.locale,
    center,
    searchQuery,
    setSearchQuery,
    isSearching,
    handleSearch,
    selectionMode,
    onSelectionModeChange: handleSelectionModeChange,
    radius,
    onRadiusChange: handleRadiusChange,
    saveSnapshot,
    onAnalyze: handleFetchAndAnalyze,
    isProcessing,
    isPolygonValid,
  };

  const sidebarBtEditorSectionProps = {
    locale: settings.locale,
    settings,
    setBtNetworkScenario,
    setBtEditorMode,
    btNetworkScenario,
    btEditorMode,
    btTopology,
    dgTopology: dgTopologySource,
    btAccumulatedByPole,
    btSummary,
    btPointDemandKva,
    btTransformerDebugById,
    btPoleCoordinateInput,
    setBtPoleCoordinateInput,
    handleBtInsertPoleByCoordinates,
    clearPendingBtEdge: () => {}, // Handled elsewhere or passed as prop
    pendingNormalClassificationPoles,
    handleResetBtTopology,
    updateBtTopology,
    updateProjectType,
    updateClandestinoAreaM2,
    handleBtSelectedPoleChange,
    handleBtSelectedTransformerChange,
    handleBtSelectedEdgeChange,
    handleBtRenamePole,
    handleBtRenameTransformer,
    handleBtSetEdgeChangeFlag,
    handleBtSetPoleChangeFlag,
    handleBtTogglePoleCircuitBreak,
    handleBtSetTransformerChangeFlag,
    btClandestinoDisplay,
    btTransformersDerived,
    requestCriticalConfirmation,
    onTriggerTelescopicAnalysis: handleTriggerTelescopicAnalysis,
    isDgOptimizing,
    dgResult,
    dgError,
    dgActiveAltIndex,
    onRunDgOptimization: handleRunDgOptimization,
    onAcceptDgAll: handleAcceptDgAll,
    onAcceptDgTrafoOnly: handleAcceptDgTrafoOnly,
    onClearDgResult: handleDiscardDgResult,
    onSetDgActiveAltIndex: setDgActiveAltIndex,
    dgIsPreviewActive: isPreviewActive,
    onSetDgIsPreviewActive: setIsPreviewActive,
    selectedPoleId,
    selectedPoleIds,
    selectedEdgeId,
    selectedTransformerId,
    onSetSelectedPoleId: setSelectedPoleId,
    onSetSelectedPoleIds: setSelectedPoleIds,
    onSetSelectedEdgeId: setSelectedEdgeId,
    onSetSelectedTransformerId: setSelectedTransformerId,
    mtTopology: mtTopology,
  };

  const sidebarAnalysisResultsProps = {
    locale: settings.locale,
    osmData,
    stats,
    analysisText,
    terrainData,
    error,
    handleDownloadDxf,
    handleDownloadCoordinatesCsv,
    isDownloading,
    showToast,
  };

  return {
    sidebarSelectionControlsProps,
    sidebarBtEditorSectionProps,
    sidebarAnalysisResultsProps,
  };
}
