export function useAppMapSelectorProps({
  center,
  btEdgeFlyToTarget,
  btPoleFlyToTarget,
  btTransformerFlyToTarget,
  radius,
  selectionMode,
  polygonPoints,
  handleMapClick,
  btEditorMode,
  mapRenderSources,
  handleBtMapClick,
  handleBtContextAction,
  pendingBtEdgeStartPoleId,
  confirmDeletePole,
  confirmDeleteEdge,
  confirmDeleteTransformer,
  handleBtSetEdgeChangeFlag,
  handleBtToggleTransformerOnPole,
  handleBtQuickAddPoleRamal,
  confirmQuickRemovePoleRamal,
  handleBtQuickAddEdgeConductor,
  confirmQuickRemoveEdgeConductor,
  handleBtSetEdgeLengthMeters,
  handleBtSetEdgeReplacementFromConductors,
  handleBtRenamePole,
  handleBtRenameTransformer,
  handleBtSetPoleVerified,
  handleBtSetPoleChangeFlag,
  handleBtTogglePoleCircuitBreak,
  handleBtSetTransformerChangeFlag,
  handleBtDragPole,
  handleBtDragTransformer,
  btCriticalPoleId,
  btNetworkScenario,
  btSectioningImpact,
  btAccumulatedByPole,
  osmData,
  handlePolygonChange,
  measurePathPoints,
  handleMeasurePathChange,
  handleKmlDrop,
  settings,
  handleMtMapClick,
  handleMtContextAction,
  handleMtDeletePole,
  handleMtDeleteEdge,
  handleMtRenamePole,
  handleMtSetPoleVerified,
  handleMtDragPole,
  handleMtSetPoleChangeFlag,
  handleMtSetEdgeChangeFlag,
  handleBtSelectedPoleChange,
  dgActiveScenario,
  isPreviewActive,
  handleBoxSelect,
}: any) {
  return {
    center,
    flyToEdgeTarget: btEdgeFlyToTarget,
    flyToPoleTarget: btPoleFlyToTarget,
    flyToTransformerTarget: btTransformerFlyToTarget,
    radius,
    selectionMode,
    polygonPoints,
    onLocationChange: handleMapClick,
    btEditorMode,
    btMarkerTopology: mapRenderSources.btMarkerTopology,
    btPopupTopology: mapRenderSources.btPopupTopology,
    onBtMapClick: handleBtMapClick,
    onBtContextAction: handleBtContextAction,
    pendingBtEdgeStartPoleId,
    onBtDeletePole: confirmDeletePole,
    onBtDeleteEdge: confirmDeleteEdge,
    onBtDeleteTransformer: confirmDeleteTransformer,
    onBtSetEdgeChangeFlag: handleBtSetEdgeChangeFlag,
    onBtToggleTransformerOnPole: handleBtToggleTransformerOnPole,
    onBtQuickAddPoleRamal: handleBtQuickAddPoleRamal,
    onBtQuickRemovePoleRamal: confirmQuickRemovePoleRamal,
    onBtQuickAddEdgeConductor: handleBtQuickAddEdgeConductor,
    onBtQuickRemoveEdgeConductor: confirmQuickRemoveEdgeConductor,
    onBtSetEdgeLengthMeters: handleBtSetEdgeLengthMeters,
    onBtSetEdgeReplacementFromConductors:
      handleBtSetEdgeReplacementFromConductors,
    onBtRenamePole: handleBtRenamePole,
    onBtRenameTransformer: handleBtRenameTransformer,
    onBtSetPoleVerified: handleBtSetPoleVerified,
    onBtSetPoleChangeFlag: handleBtSetPoleChangeFlag,
    onBtTogglePoleCircuitBreak: handleBtTogglePoleCircuitBreak,
    onBtSetTransformerChangeFlag: handleBtSetTransformerChangeFlag,
    onBtDragPole: handleBtDragPole,
    onBtDragTransformer: handleBtDragTransformer,
    criticalPoleId: btCriticalPoleId,
    loadCenterPoleId:
      btNetworkScenario === "projeto"
        ? (btSectioningImpact.suggestedPoleId ?? null)
        : null,
    accumulatedByPole: btAccumulatedByPole,
    osmData: osmData,
    onPolygonChange: handlePolygonChange,
    measurePath: measurePathPoints,
    onMeasurePathChange: handleMeasurePathChange,
    onKmlDrop: handleKmlDrop,
    mapStyle: settings.mapProvider === "satellite" ? "satellite" : "dark",
    mtMarkerTopology: mapRenderSources.mtMarkerTopology,
    mtPopupTopology: mapRenderSources.mtPopupTopology,
    mtEditorMode: settings.mtEditorMode ?? "none",
    onMtMapClick: handleMtMapClick,
    onMtContextAction: handleMtContextAction,
    onMtDeletePole: handleMtDeletePole,
    onMtDeleteEdge: handleMtDeleteEdge,
    onMtRenamePole: handleMtRenamePole,
    onMtSetPoleVerified: handleMtSetPoleVerified,
    onMtDragPole: handleMtDragPole,
    onMtSetPoleChangeFlag: handleMtSetPoleChangeFlag,
    onMtSetEdgeChangeFlag: handleMtSetEdgeChangeFlag,
    onBtSelectPole: handleBtSelectedPoleChange,
    dgScenario: dgActiveScenario,
    dgGhostMode: isPreviewActive && dgActiveScenario != null,
    onBoxSelect: handleBoxSelect,
    locale: settings.locale,
    layerConfig: settings.layers,
  };
}
